# Generated by Django 4.1.3 on 2022-11-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='age',
            field=models.IntegerField(verbose_name='Artistes Age'),
        ),
    ]
